### ISSUE TITLE
Cannot add user to the render system group

### ISSUE THREAD

**Issue by MidnessX** [coreos/butane#411] opened 2022-12-27 13:07 UTC
I'm trying to add a user to the ``render`` group as it should have access to a graphics card passed through by the host.

However, this has proven to be impossible as writing
```
[...]
passwd:
  users:
    - name: myuser
      groups:
        - render
[...]
```
results in ``ignition-files.service`` failing due to the ``render`` group missing, and manually creating the group by doing
```
[...]
passwd:
  groups:
    - name: render
      system: true
  users:
    - name: myuser
      groups:
        - render
[...]
```
instead results in  ``ignition-files.service`` failing due to the ``render`` group already existing.

**Comment by bgilbert** [comment] 2023-01-29 02:50
Thanks for the report.  This is https://github.com/coreos/fedora-coreos-tracker/issues/155.  The issue is that `usermod` doesn't know to copy the `render` group from `/usr/lib/group` to `/etc/group` before trying to add a user to it.  At the moment I believe you'd need to write a `ConditionFirstBoot=true` systemd unit which does something like `grep ^render: /usr/lib/group >> /etc/group && usermod -G render -a core`.

Closing as duplicate of https://github.com/coreos/fedora-coreos-tracker/issues/155

**Closed by bgilbert** 2023-01-29 02:50 UTC
Labels: bug, jira
